[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.20"
optimizer = true
optimizer-runs = 200

remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[rpc_endpoints]
arbitrum = "wss://arbitrum-one-rpc.publicnode.com"
base = "https://mainnet.base.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
